
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by CSGenerator.
// </auto-generated>
//------------------------------------------------------------------------------
using SharpKit.JavaScript;

[assembly: JsExport(Minify = false, DefaultFilename = "Assets/JavaScript/GameLogicCode.bytes")]

#region JsType
[assembly: JsType(TargetTypeName = "BasicVariableTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "CollectionItem", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "CollectionTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "DateTimeTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "IOTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JsonTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JsonTest+Entity", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JsonTest+EntityAction", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JsonTest+EntityList", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LambdaTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LingQTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "MathTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "StringBuilderTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "StringTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TimeSpanTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "DelegateTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "DictionaryTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "EncodingTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "LoginMgr", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TestLogin", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "EventTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ListTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "PerformanceTest1", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SampleViewer", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SampleViewer+stScene", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "V3Test", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AwakeA", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AwakeB", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AwakeC", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "ComponentTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "MentosKXT", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TEnemy", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TEnemyBase", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "TestCoroutine", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "GUITest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "jsimp.Reflection", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JSImpTest1", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "JSImpTest1+Person", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "XmlParser", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "MiscTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "AnimationCurveTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Car", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SerializeSimple", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SerializeStruct", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "SerializeStruct+AppleInfo", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Wheel", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "Wheel+Pos", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "StreamTest", Mode = JsMode.Clr)]
[assembly: JsType(TargetTypeName = "XmlTest", Mode = JsMode.Clr)]

#endregion